### ISSUE TITLE
Consider adding license

### ISSUE THREAD

**Issue by Andrew15-5** [ankostis/gnome-shell-quick-lang-switch#10]
If you don't really care about license, you can choose one of these:
https://choosealicense.com/licenses/unlicense/
https://choosealicense.com/licenses/wtfpl/

You can find a big list of licenses to choose from at https://choosealicense.com/appendix/.

**Comment by ankostis** [comment]
Thank you, i do care about the licenses, therefore i choose AGPL.  If we don't care, big corporations win.
