### ISSUE TITLE
Support GNOME 45

### ISSUE THREAD

**Issue by MAXZVER** [ankostis/gnome-shell-quick-lang-switch#12]

**Comment by aplab** [comment]
I tried to add 45 to metadata.json myself but it doesn’t work anymore (

**Comment by ankostis** [comment]
For version 45 it needs extensive retrofitting to ESM, try testing #13.

**Comment by aplab** [comment]
> For version 45 it needs extensive retrofitting to ESM, try testing #13.

Thank you very much! It works for me!

**Comment by dsbasko** [comment]
> > For version 45 it needs extensive retrofitting to ESM, try testing #13.
> 
> Thank you very much! It works for me!

Can you make a pull request?

**Comment by aplab** [comment]
> > > For version 45 it needs extensive retrofitting to ESM, try testing #13.
> > 
> > 
> > Thank you very much! It works for me!
> 
> Can you make a pull request?

pull request already exists here https://github.com/ankostis/gnome-shell-quick-lang-switch/pull/13

**Comment by shrralis** [comment]
And now it's GNOME 47.

**Comment by ankostis** [comment]
Just released for v47
