### ISSUE TITLE
Invite more maintainer(s) for this project

### ISSUE THREAD

**Issue by ankostis** [ankostis/gnome-shell-quick-lang-switch#14]
I'm a python developer, not a js one.  Nevertheless,  the itch was so unbearable that i studied just the necessary lib code to craft this extension.  Since GnomeShell v45(#13) and the [call  for test-cases from "Extensions Rebooted" ](https://gitlab.gnome.org/World/ShellExtensions/extensions-rebooted/-/wikis/home),
the knowledge level required has surpassed me.
I'm calling for volunteer(s) to help me maintain this project.

@thankjura are you interested to maintain this project?
I'm ready to release v9, would you like me to wait to do it together (share credentials, etc)?

Anybody else?
(past contributors would be prioritized)

**Comment by thankjura** [comment]
Yes. I don't mind, I can maintain compatibility with new versions of gnome.

**Comment by ankostis** [comment]
Yury invited.

**Comment by ankostis** [comment]
Have [asked SO](https://stackoverflow.com/questions/77487447/how-to-maintain-a-gnome-extension-collaboratively) how can multiple maintainers collaborate when uploading extensions without shared credentials.
