### ISSUE TITLE
The (un)focus issue isn't fixed

### ISSUE THREAD

**Issue by Andrew15-5** [ankostis/gnome-shell-quick-lang-switch#16]
Hi, I tried to check if the focus problem is fixed when using this extension, but unfortunately it doesn't appear to be fixed. My simple test is to go to https://duckduckgo.com/?q=test and then enter the search bar and start typing in one language. The search suggestions will appear. After pressing Super+Space, the search suggestions disappear and the search bar is now unfocused. Same as if no extension is used. So my question is: is the focus problem truly fixed, or it just unfocuses for a much shorter period of time? If it's the latter, then you should update the description, to remove the misleading information.

Quote from the https://extensions.gnome.org/extension/4559/quick-lang-switch/:
> It fixes also focus issues with the active window.

**Comment by ankostis** [comment]
Very strange, it shouldn't affect the focuds at all.
Could it be the shortcut combination you have chosen?
Maybe when pressing modifiers, they interfere with the suggestion?
Which shortcut have you bound it?

**Comment by Andrew15-5** [comment]
> Which shortcut have you bound it?

It's all in the message. Super+Space.

I'm using Firefox on Pop!_OS 22.04 with GNOME 42.

I've checked, and just holding the Super key makes search bar unfocus.

I've been using this extension: https://github.com/osamuaoki/inputmethod-shortcuts. The shortcuts also involve pressing Super key: Super+Alt+\<letter>. The unfocussing also occur. But now I tried using Ctrl+Shift+\<letter> and the unfocus only occur after the shortcut is pressed, i.e., the element still has focus while the Ctrl+Shift are pressed.

So my guess is that Super key does affect focusing just by itself, which is strange, but also changing the keyboard layout in any way also affects the focus.

I tried a Ctrl+Shift+J with this extension and yeah, it still only unfocuses after all 3 keys are pressed. So both extensions behave the same way for me.

**Comment by ankostis** [comment]
I can't reproduce it. 
Have you checked the browser is not hadling this shortcut and/trying other shortcuts?

Anyhow, the extension does not do anything to affect the focus, so please keep searching the culprit, it should be in common with the other _inputmethod-shortcuts_ extension, and report it here for future reference.

**Comment by ankostis** [comment]
Assume report invalid.
