### ISSUE TITLE
switch-input-source-backward need to be handled as well, in addition to switch-input-source

### ISSUE THREAD

**Issue by alexandrustinov** [ankostis/gnome-shell-quick-lang-switch#4]
1) The "switch-input-source-backward" binding should be handled in addition to "switch-input-source".

You can see it using next command line output:

    gsettings list-recursively org.gnome.desktop.wm.keybindings|grep switch-input                                                                             

By default Super+Space switches layout forward, while Super+Shift+Space switches it backward.
Suppressing of the popup window works for "forward" switching at the moment, while Super+Shift+Space still shows the popup.

It also can be reproduced using next command line settings for Ctrl+Shift switch:

    gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Shift>Ctrl_L']" 
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Ctrl>Shift_L']" 
 
or next ones for Alt+Shift keystroke:

    gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Shift>Alt_L']" 
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Alt>Shift_L']" 

That way Ctrl+Shift or Alt+Shift keystroke will act just like it works in Windows, but the popup window will still appear for each second Ctrl+Shift or Alt+Shift stroke from time to time (not each time though).

2) Also it would be nice to integrate that <Shift>Ctrl_L and <Ctrl>Shift_L (or <Shift>Alt_L and <Alt>Shift_L) hack somewhere in plugin settings as option, because it's not obvious how to obtain Windows like keyboard layout switching "out of the box". 
The default Super+Space combination is not so "quick" as for me.

**Comment by ankostis** [comment]
1. I'm not surprised that i hadn't handled also the shift(backwards) case, i didn't know this command existed.  But I'm surprised that no one ever reported it.
2. Will fix it. 

3. I don't know the Ctrl_L hacks? Can you give me some hints, or an merge request?

**Comment by alexandrustinov** [comment]
1. I suppose that the backward switch is rarely (never) used because most of users just cycle between native and English language, it's enough to press Super+Space for that
2. TA in advance
3. In short - it's not possible to assign Ctrl+Shift or Alt+Shift as language switch sequence using Gnome Settings tool. 
Meanwhile it's possible to do that using Gnome Tweaks Utility (it has Keyboard & Mouse > Additional Layout options > Switching to another layout > [ ] Ctrl+Shift checkbox). 
It will work, though it will be not possible to see changing in status bar icon, it will always show  'en'  (Centos Stream 9 / Gnome Standard Wayland, other distros also seems are affected).

As workaround it's possible to execute the next commands from command line (I mentioned them above), after that keyboard layout  switch will work as expected and the icon in status bar will change accordingly:

    gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Shift>Ctrl_L']" 
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Ctrl>Shift_L']" 

I initially found the gsettings hack here https://losst.pro/raskladka-klaviatury-v-ubuntu
sorry for the Russian text, but it could be autotranslated using Google Chrome Translate option.

Also next link might explain the same issue better:
https://askubuntu.com/questions/967364/ubuntu-17-10-and-later-cant-change-the-input-switching-shortcut-to-altshift

That way I found existence of switch-input-source-backward and faced with the popup which had to be suppressed by your plugin.

So it will be great to create small setup dialog for your plugin which will allow to choose proper settings for language switcher (default Super+Space, Ctrl+Shift, Alt+Shift or PrtSc/SysRq) . 
I would raise PR from my side though I never developed the GNOME extensions, it will take some time to deep-in there.

**Comment by Alt37** [comment]
I've made a quick patch adding new const for "switch-input-source-backward" shortcut and duplicating code for ""switch-input-source". I didn't add "disable" part because of issue #5 

```
--- extension.js
+++ extension.js
@@ -26,6 +26,7 @@
 const { Gio, Meta, Shell } = imports.gi
 const Main = imports.ui.main;
 const SWITCH_SHORTCUT_NAME = 'switch-input-source'
+const SWITCH_BACK_SHORTCUT_NAME = 'switch-input-source-backward'
 const InputSourceManager = imports.ui.status.keyboard.getInputSourceManager();
 
 class Extension {
@@ -35,10 +36,16 @@
     enable() {
         log(`enabling extension '${Me.metadata.name}':  bypassing language switcher popup.`);
         Main.wm.removeKeybinding(SWITCH_SHORTCUT_NAME);
+        Main.wm.removeKeybinding(SWITCH_BACK_SHORTCUT_NAME);
         Main.wm.addKeybinding(SWITCH_SHORTCUT_NAME,
                               new Gio.Settings({ schema_id: "org.gnome.desktop.wm.keybindings" }),
                               Meta.KeyBindingFlags.NONE,
                               Shell.ActionMode.ALL,
+                              this._quickSwitch);
+        Main.wm.addKeybinding(SWITCH_BACK_SHORTCUT_NAME,
+                              new Gio.Settings({ schema_id: "org.gnome.desktop.wm.keybindings" }),
+                              Meta.KeyBindingFlags.NONE,
+                              Shell.ActionMode.ALL,
                               this._quickSwitch);
     }
```
 
To apply this patch you need to perform such actions in a Terminal
1) Go to extension directory
`cd  "~/.local/share/gnome-shell/extensions/quick-lang-switch@ankostis.gmail.com/"`
2) Create patch file
`nano disable--switch-input-source-backwards.patch`
3) Paste content of the patch (above) with right mouse click (or Ctrl+Shift+V) and save it with Ctrl+S
3) Apply patch (and backup original file as extension.js.orig)
`patch -b < disable--switch-input-source-backwards.patch`

**Comment by ankostis** [comment]
[v8](https://github.com/ankostis/gnome-shell-quick-lang-switch/releases/tag/v8) fixed this
