### ISSUE TITLE
Switcher popup breaks after disabling the extension (needs gnome-shell restart)

### ISSUE THREAD

**Issue by xalt7x** [ankostis/gnome-shell-quick-lang-switch#5]
OS: Ubuntu 22.04.1
GNOME: 42.5
Session: X11

Steps to reproduce (with default key-binding <Super> + Space):
1) Enable, then disable extension without gnome-shell restart
2) Try to hold "Super" and press "Space" multiple times

Expected result:
While you're holding "Super" pop-up remains on the screen and you can switch languages with "Space"

Actual Result:
Pop-up disappears immediately after you've pressed "Space" the second time.

**Comment by ankostis** [comment]
I can't reproduce :-( 
At least not when tested on _Wayland_.
Also tested with AND without a custom key bound to the switching.
