### ISSUE TITLE
Disabling the extension breaks default GNOME layout switching behavior (bug)

### ISSUE THREAD

**Issue by Andrew15-5** [ankostis/gnome-shell-quick-lang-switch#8]
I disabled the extension and I can't switch to a different layout other than 2 lastly used ones (I have currently 3 layouts/languages) unless I click on the different one from the popup or from the top bar.

Restarting GNOME shell (Alt+F2>r) fixes the problem.

**Comment by ankostis** [comment]
Any hints on how to fix this?

**Comment by ankostis** [comment]
Dupe of #5.
(thanks for the **[F2]** tip)

**Comment by ankostis** [comment]
FYI v8 fixed this.
